[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/book"
  to = "/.netlify/functions/book"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
